spring:
  application:
    name: consumer-service
  lifecycle:
    timeout-per-shutdown-phase: "2m"

server:
  port: 8081
  http2:
    enabled: true

consumer-service:
  vehicle-geo-location:
    host: localhost
    port: 9000

geo-location:
  waitTime: 4